title:              Clean Blog
email:              report@speedwp.ch
description:        A Blog Theme by Start Boorap
author:             SpeedWP
baseurl:            "/blog"
url:                "https://speedwp.github.io"

# Social Profiles
twitter_username:   SpeedWP
github_username:    SpeedWP
facebook_username:  SpeedWP.ch
linkedin_username:  SpeedWP

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
